orbs:
  react: thefrontside/react@0.2.0
version: 2.1
executors:
  description: Node 10 runtime environment
  sad: 'sad'
workflows:
  push:
    jobs:
      - react/install
      - react/build:
          requires:
            - react/install
      - react/test:
          requires:
            - react/install