orbs:
  react: thefrontside/react@0.2.0
version: 2.1
executors:
  default:
    description: |
      Node 16 runtime environment
    docker:
    - image: circleci/node:16.3.0
    parameters:
      node:
        default: "16.3.0"
        type: string
workflows:
  push:
    jobs:
      - react/install
      - react/build:
          requires:
            - react/install
      - react/test:
          requires:
            - react/install