orbs:
  react: thefrontside/react@0.2.0
version: 2.1
executors:
  default:
    description: Node 10 runtime environment
workflows:
  push:
    jobs:
      - react/install
      - react/build:
          requires:
            - react/install
      - react/test:
          requires:
            - react/install